### ISSUE TITLE
Commands Hang/Fail

### ISSUE THREAD

**Issue by joeguilmette** [Stefouch/sebedius-myz-discord-bot#18]
Hey there! I've noticed that many commands will hang and fail out.

Is this a server resources issue?

**Comment by Stefouch** [comment]
Could you expand on the issue?

Which commands are hanging?
Does it happen all the time or at certain time of the day?

Meanwhile, I've restarted the bot's process on its server. Hope it can help.

I use a free server on Heroku (which uses Amazon Web Services - AWS).
After a quick check, the AWS got a few problems 6 hours ago. It might be the cause if the bot response returned to normal since.

**Comment by joeguilmette** [comment]
Nothing too serious, I haven't noticed any patterns. But I have seen commands just not get a response at all.

**Comment by joeguilmette** [comment]
If I can pin it down I'll reopen this ticket.
